---
title: "R Notebook"
output: html_notebook
---

```{r}
25%%3
5+6*8/4 # Mixtas

```

```{r}
x = 10
z = -15
y = z^2+x^2 
y
```

```{r}
my_character = "universe"
my_logical = FALSE

my_character
my_logical

class(my_logical)
```
```{r}
numeric_vector = c(2,-25,50)
vector_caracter = c("uno", "dos", "tres")
vector_booleano = c(TRUE, FALSE, TRUE)

numeric_vector
vector_caracter
vector_booleano
```
```{r}
poker_vector = c(140,-48,23,10.5)
names(poker_vector) = c("uno", "dos", "tres", "cuatro")
poker_vector
```

```{r}
total_vector = sum(poker_vector) 
total_vector

poker_vector[3]
poker_vector[c(2,1)]

poker_start = poker_vector[c("uno", "dos", "cuatro")]
poker_start
mean(poker_start)

selection_vector = poker_vector<0
selection_vector
```
Matrices
```{r}
matrix(1:9 , byrow = TRUE, nrow = 3)
```

```{r}
new_hope = c(460.998, 314.4)
empire_strike = c(2980.475, 247.900)
return_jedi = c(309.306, 165.8)

box_office = c(new_hope, empire_strike, return_jedi)
box_office

stars_wars_matrix = matrix(box_office, byrow = TRUE, nrow = 3)


region = c("US", "NON-US")
titles = c("A new hope", "The empire strikes back", "Return of jedi")

colnames(stars_wars_matrix) = region
rownames(stars_wars_matrix) = titles 
stars_wars_matrix
```
```{r}
worldwide_vector = rowSums(stars_wars_matrix)
worldwide_vector

all_wars_variable = cbind(stars_wars_matrix, worldwide_vector)
all_wars_variable


worldwide_cols = colSums(all_wars_variable)
worldwide_cols

all_wars_variable = rbind(all_wars_variable, worldwide_cols)
all_wars_variable
```

Elementos de una matriz

```{r}
non_us_all = all_wars_variable[1:3,2]
non_us_all

mean(non_us_all)

us_all = all_wars_variable[1:3,1]
us_all = us_all*0.12
us_all

```

FACTORES

```{r}
sex_vector= c("male", "female", "female", "male", "female")
factor_sex_vector = factor(sex_vector)
factor_sex_vector

temperature_vector = c("high", "low", "high", "medium")
factor_temperature = factor(temperature_vector, order = TRUE, levels = c("low", "medium", "high"))
factor_temperature


survey_vector = c("M", "F", "F", "M", "M")
factor_survey_vector = factor(survey_vector)

factor_survey_vector

levels(factor_survey_vector) = c("Femele", "Male")
factor_survey_vector
```
Factor sumarizado

```{r}
summary(survey_vector) 
summary(factor_survey_vector)

male = factor_survey_vector[1]
male 

female = factor_survey_vector[2]
female

speed_vector = c("medium", "slow", "slow", "medium", "fast")
factor_speed_vector = factor(speed_vector, ordered = TRUE, levels = c("slow", "medium", "fast"))
factor_speed_vector

da2 = factor_speed_vector[2]
da3 = factor_speed_vector[1]

da2
da3

da2 < da3

```

